apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-mongo
  template:
    metadata:
      labels:
        app: node-mongo
    spec:
      containers:
        - name: node-app
          image: kujtimpllana/node-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
        - name: mongodb
          image: mongo:6.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
