apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-mongo
  template:
    metadata:
      labels:
        app: node-mongo
    spec:
      containers:
        - name: node-app
          image: kujtimpllana/node-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: node-mongo-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: node-mongo-secret
                  key: DB_PASS
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: node-mongo-secret
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: node-mongo-config
                  key: DB_PORT
        - name: mongodb
          image: mongo:6.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: node-mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: node-mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: node-mongo-config
                  key: DB_NAME

          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
        - name: mongo-express
          image: mongo-express:1.0.2-20-alpine3.19
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: node-mongo-config
                  key: MONGO_DB_SERVER
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: node-mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: node-mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                secretKeyRef:
                  name: node-mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: ME_CONFIG_BASICAUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: node-mongo-secret
                  key: ME_USER
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: node-mongo-secret
                  key: ME_PASS
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
