apiVersion: v1
kind: Secret
metadata:
  name: node-mongo-secret
type: Opaque
data:
  DB_USER: cm9vdA==
  DB_PASS: ZXhhbXBsZQ==
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_INITDB_ROOT_PASSWORD: ZXhhbXBsZQ==
  ME_USER: YWRtaW4=
  ME_PASS: c2VjcmV0cGFzc3dvcmQ=
  DB_NAME: dGVzdGRi
